name: lazagne
category: credentials
version: "2.4.6"
description: Retrieve passwords stored on a local machine from many apps/browsers.
tags: [creds, loot, post-exploitation, windows]
homepage: https://github.com/AlessandroZ/LaZagne
files:
  - dest: lazagne.exe
    os: windows
    arch: amd64
    exec: false
    url: release://binaries/lazagne_2.4.6.exe
